### ISSUE TITLE
Friends embed should have more categorization options

### ISSUE THREAD

**Issue by admutin** [ps2gg/ps2.gg#80]
### I'm submitting a... 

- [ ] Bug report
- [x] Feature request
- [ ] Documentation request

### Current behavior 
The Friends retrieved from the /friends Command are only split in faction

### Expected behavior 
The Friends should be categorized into Faction, Profession, Server, Outfit, BR.
Offline Friends can be shown optionally.

### Definition of Done 

- [Universal Definition of Done](https://github.com/ps2gg/ps2.gg/blob/master/docs/standards/Definition-Of-Done.md) is adhered to

##

**Comment by Kaptard** [comment]
I believe keeping the default server sorting makes most sense for the main use case, where someone simply wants to know where their friends are playing.

More specific player information would be useful for the upcoming "Call friends" feature. Users could then choose a subsection of players by their preferred playstyles, skill levels, etc.

**Comment by Kaptard** [comment]
After more planning, it turns out this won't be relevant until we've implemented elo, at which point we also have the overlay to work with. Will open a new issue when it becomes relevant again.
