### ISSUE TITLE
Add whois command to Jaeger

### ISSUE THREAD

**Issue by Kaptard** [ps2gg/ps2.gg#91]
### I'm submitting a... 

- [ ] Bug report
- [x] Feature request
- [ ] Documentation request

### Current behavior 
There is no way for PSB admins to see who's verified as whom without digging through logs.

### Expected behavior 
On top of /whoami (#90), there should be a /whois command to make account management easier for PSB admins.

### Definition of Done 

- [Universal Definition of Done](https://github.com/ps2gg/ps2.gg/blob/master/docs/standards/Definition-Of-Done.md) is adhered to

##

**Comment by admutin** [comment]
who should be able to use this command?
do you want to tie it to a hardcoded role or something?

**Comment by Kaptard** [comment]
> who should be able to use this command? do you want to tie it to a hardcoded role or something?

We would only respond to PSB Admins (role id: 332587654111821827)
